import backToTop from "../js/modules/backToTop.js";
import AosModule from "../js/modules/AosModule.js";
import PopupModule from "../js/modules/PopupModule.js";
import ScrollModule from "../js/modules/ScrollModule.js";
import SliptModule from "../js/modules/SliptModule.js";
import ScrollParallax from "../js/modules/ScrollParallax.js";
import ToggleMega from "../js/modules/ToggleMega.js";
import ToggleInfo from "../js/modules/ToggleInfo.js";
import ToggleEditProduct from "../js/modules/ToggleEditProduct.js";
import SelectQtyModule from "../js/modules/SelectQtyModule.js";
import StickyHeader from "../js/modules/StickyHeader.js";
import TogglePassword from "../js/modules/TogglePassword.js";
import Select2Module from "../js/modules/Select2Module.js";
import ChoseFileModule from "../js/modules/ChoseFileModule.js";
import SwiperModule from "../js/modules/SwiperModule.js";
import AccordionModule from "../js/modules/AccordionModule.js";
import GalleryModule from "../js/modules/GalleryModule.js";
import CopyTextModule from "../js/modules/CopyTextModule.js";
import TabModule from "../js/modules/TabModule.js";
import CollapseProductTable from "../js/modules/CollapseProductTable.js";
import DatePickerModule from "../js/modules/DatePickerModule.js";
import ToggleDetailHistoryProduct from "../js/modules/ToggleDetailHistoryProduct.js";
import SetDefaultModule from "../js/modules/SetDefaultModule.js";
import ProgressModule from "../js/modules/ProgressModule.js";
import ToggleTooltip from "../js/modules/ToggleTooltip.js";
import ToggleSortPro from "../js/modules/ToggleSortPro.js";

window.addEventListener("DOMContentLoaded", () => {
  backToTop();
  AosModule();
  PopupModule();
  ScrollModule();
  SliptModule();
  ScrollParallax();
  ToggleMega();
  ToggleInfo();
  ToggleEditProduct();
  SelectQtyModule();
  StickyHeader();
  TogglePassword();
  Select2Module();
  ChoseFileModule();
  SwiperModule();
  AccordionModule();
  GalleryModule();
  CopyTextModule();
  TabModule();
  CollapseProductTable();
  ToggleDetailHistoryProduct();
  SetDefaultModule();
  ProgressModule();
  ToggleTooltip();
  ToggleSortPro();
  DatePickerModule();
});
